apiServer:
  resources:
    requests:
      cpu: "2"
      memory: 6Gi
    limits:
      cpu: "2"
      memory: 6Gi
frontend:
  resources:
    requests:
      cpu: 150m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 128Mi
ingress:
  enabled: true
  hostname: "localhost"
  ingressClassName: "nginx"